/**
 * APEX Research Agent — study-file scaffold template.
 *
 * Generates the *boilerplate* for a new scripts/research/run*.mts study
 * file — the safety-critical structural parts (the --evaluate-sealed flag
 * gate, the gatePolicy thresholds, the dev-only-by-default data loader
 * call) — so every new candidate script starts from a correct, consistent
 * skeleton instead of being hand-copied (and occasionally miscopied) from
 * whichever old script is open.
 *
 * This deliberately does NOT generate the actual signal/backtest logic —
 * that stays a human (or human-and-assistant, in an actual coding session
 * with the real repo open) task, same as every other study in this
 * project. The TODO markers are the boundary: everything above them is
 * meant to be used as-is; everything below is a stub.
 */

export interface ScaffoldOptions {
  /** Candidate id, e.g. "candidate-7-funding-carry" */
  id: string;
  /** One-line hypothesis / family description */
  hypothesis: string;
  /** PascalCase name used for the exported function / file purpose, e.g. "FundingCarry" */
  studyName: string;
}

export function renderStudyTemplate(opts: ScaffoldOptions): string {
  const { id, hypothesis, studyName } = opts;
  const safeHypothesis = hypothesis.replace(/\r?\n/g, ' ').replace(/\*\//g, '* /');
  return `/**
 * Study: ${id}
 * Hypothesis: ${safeHypothesis}
 *
 * SCAFFOLD — generated by scripts/research-agent. Everything above the
 * "=== fill in below ===" markers is safety-critical structure shared by
 * every study in this project and should be left as-is. Everything below
 * is a stub for you (or you-and-an-assistant, with the real repo and data
 * loaders open) to actually implement.
 *
 * Convention this follows (see README.md in scripts/research-agent/ and
 * any existing scripts/research/*.mts file for the pattern this mirrors):
 *   - loadDevelopment*() only, by default — never touches the sealed set
 *   - a --evaluate-sealed CLI flag is the ONLY way this file's sealed
 *     branch runs, and only openHoldout.mts is supposed to ever pass it
 *   - a gatePolicy block encodes the mission thresholds so every study
 *     reports against the same bar (net>0, PF>1, maxDD<=15%)
 */

// TODO: wire this to the same in-sample/development loader your other
// scripts/research/*.mts files use (e.g. loadDevelopmentOHLCV, loadDevelopmentFunding).
// This scaffold intentionally does not import or fabricate one.
declare function loadDevelopmentData(): Promise<unknown>;

// TODO: wire this to the same sealed 2024-2025 holdout loader your other
// scripts/research/*.mts files use. This function must ONLY be reachable
// through the --evaluate-sealed branch below — never call it otherwise.
declare function loadSealedHoldoutData(): Promise<unknown>;

interface GatePolicy {
  minNetReturnPct: number;
  minProfitFactor: number;
  maxDrawdownPct: number;
  minTrades: number;
}

// Repository promotion gate. This is deliberately stricter than the broad
// mission drawdown cap used by some exploratory reports: maxDD <= 13% and at
// least 30 trades, matching the structural-profitability promotion policy.
const gatePolicy: GatePolicy = {
  minNetReturnPct: 0,
  minProfitFactor: 1,
  maxDrawdownPct: 13,
  minTrades: 30,
};

interface StudyResult {
  id: string;
  evaluatedSealed: boolean;
  net: number;
  pf: number;
  maxDD: number;
  trades: number;
  sharpe?: number;
  passedGate: boolean;
}

function evaluateGate(r: Omit<StudyResult, 'passedGate' | 'id' | 'evaluatedSealed'>): boolean {
  return r.net > gatePolicy.minNetReturnPct
    && r.pf > gatePolicy.minProfitFactor
    && r.maxDD <= gatePolicy.maxDrawdownPct
    && r.trades >= gatePolicy.minTrades;
}

async function runStudy(evaluateSealed: boolean): Promise<StudyResult> {
  // === fill in below ===
  // TODO: replace this whole function body with the real backtest for
  // "${safeHypothesis}". Suggested shape, matching the existing convention:
  //   1. const data = evaluateSealed ? await loadSealedHoldoutData() : await loadDevelopmentData();
  //   2. compute the signal / positions from data
  //   3. run the backtest / walk-forward harness this project already has
  //   4. compute net, pf (profit factor), maxDD, trades, and optionally sharpe
  //   5. return { id: '${id}', evaluatedSealed, net, pf, maxDD, trades, sharpe, passedGate: evaluateGate({...}) }
  throw new Error(
    '${studyName} study is a scaffold — implement runStudy() before running this file. ' +
    'See the TODO comments above.',
  );
  // === fill in above ===
}

async function main(): Promise<void> {
  const evaluateSealed = process.argv.includes('--evaluate-sealed');
  if (evaluateSealed) {
    console.error(
      '[${id}] --evaluate-sealed was passed. This should only ever happen via ' +
      'scripts/research-agent/openHoldout.mts, after the human confirmation gate. ' +
      'Proceeding because this scaffold does not re-implement that gate itself — ' +
      'the gate lives in openHoldout.mts, not in individual study files.',
    );
  }
  const result = await runStudy(evaluateSealed);
  // Print the result as the LAST thing this script writes to stdout, as
  // trailing JSON — scripts/research-agent/runQueuedStudies.mts and
  // summarizeRuns.mts both look for exactly this pattern.
  console.log(JSON.stringify(result, null, 2));
  process.exit(result.passedGate ? 0 : 0); // exit 0 either way: a clean run that failed the gate is not a crash
}

main().catch((err) => {
  console.error('[${id}] study failed:', err);
  process.exit(1);
});
`;
}
