import { readFileSync } from 'node:fs';
import { loadTypeScript } from './lib/loadTypeScript.mjs';

const ts = loadTypeScript();
const files=['src/lib/storage.ts','src/lib/watchlistFavorites.ts','src/App.tsx','src/pages/alerts/AlertsPage.tsx','src/pages/settings/SettingsPage.tsx','src/pages/strategies/StrategyPage.tsx','src/pages/strategies/StrategyModelWorkspace.tsx','src/pages/watchlist/WatchlistPage.tsx','src/pages/help/HelpPage.tsx','src/pages/screener/screenerPersistence.ts','src/pages/screener/ScreenerPage.tsx','src/pages/backtesting/backtestPersistence.ts','src/pages/backtesting/useBacktestingPresetsAndNotes.ts','src/services/telegram.ts','src/components/TelegramSettingsPanel.tsx'];
const s=Object.fromEntries(files.map(f=>[f,readFileSync(f,'utf8')])); const fail=[]; const c=(n,o)=>{console.log(`${o?'PASS':'FAIL'} ${n}`);if(!o)fail.push(n)};
const storage=s['src/lib/storage.ts'], watchStorage=s['src/lib/watchlistFavorites.ts'], alerts=s['src/pages/alerts/AlertsPage.tsx'], app=s['src/App.tsx'], settings=s['src/pages/settings/SettingsPage.tsx'], strategy=s['src/pages/strategies/StrategyPage.tsx'], model=s['src/pages/strategies/StrategyModelWorkspace.tsx'], watch=s['src/pages/watchlist/WatchlistPage.tsx'], help=s['src/pages/help/HelpPage.tsx'], screen=s['src/pages/screener/screenerPersistence.ts'], screenPage=s['src/pages/screener/ScreenerPage.tsx'], bt=s['src/pages/backtesting/backtestPersistence.ts'], bth=s['src/pages/backtesting/useBacktestingPresetsAndNotes.ts'], telegram=s['src/services/telegram.ts'], telegramPanel=s['src/components/TelegramSettingsPanel.tsx'];
c('fresh install does not present built-in alert defaults as saved rules',storage.includes("if (!raw) return [];")&&storage.includes("if (typeof window === 'undefined') return [];"));
c('settings persistence reports failure to caller',storage.includes('export function saveSettings(settings: TerminalSettings): boolean')&&settings.includes("Preferences were not saved because browser persistence is unavailable."));
c('alert persistence is authoritative before UI success',storage.includes('export function saveAlertRules(rules: AlertRule[]): boolean')&&app.includes("if (!saveAlertRules(nextRules)) return false")&&alerts.includes('Alert rule not saved'));
c('alert session trigger count is not double-counted with durable trigger count',alerts.includes('const triggeredCount = props.activeAlerts.length;')&&!alerts.includes('Saved count plus this session'));
c('Strategy Studio bookmark is not mislabeled Save as Preset',model.includes('Bookmark Strategy')&&!model.includes('Save as Preset'));
c('Strategy bookmark success requires storage success',strategy.includes('if (!writeBookmarks(next))')&&strategy.includes('Bookmark was not saved'));
c('empty watchlist does not masquerade as full-market performance',watch.includes('const performanceSource = watchlist;')&&watch.includes('No saved markets'));
c('watchlist persistence failure is observable and suppresses success UI',watchStorage.includes('persisted: false')&&watch.includes("title: 'Watchlist not saved'")&&watch.includes('if (!result.persisted)'));
c('Market Cap sorting does not substitute turnover for missing market cap',!watch.includes('(marketCap(b) ?? b.turnover24h)')&&watch.includes('if (capA === null) return 1;'));
c('opening Help academy track is not completion/progress',help.includes('opening it does not count as completion or progress')&&help.includes('ACADEMY_OPENED_KEY'));
c('Help academy persistence failure is surfaced before local state changes',help.includes("title: 'Academy state not saved'")&&help.indexOf('window.localStorage.setItem(ACADEMY_OPENED_KEY')<help.indexOf('setAcademyOpened(next)'));
c('Screener storage writes return observable success',screen.includes('): boolean')&&screenPage.includes("title: 'Screen not saved'"));
c('Backtest preset/note write failure is observable',bt.includes("throw new Error('backtest_preset_persistence_failed')")&&bt.includes("throw new Error('backtest_note_persistence_failed')")&&bth.includes("title: 'Preset not saved'")&&bth.includes("title: 'Evidence note not saved'"));
c('Telegram preference persistence failure is returned and surfaced',telegram.includes('export function saveTelegramPrefs(prefs: TelegramPrefs): boolean')&&telegramPanel.includes('if (!saveTelegramPrefs(next))')&&telegramPanel.includes('browser persistence is unavailable'));
for(const f of files){const out=ts.transpileModule(s[f],{compilerOptions:{jsx:ts.JsxEmit.ReactJSX,target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext},fileName:f,reportDiagnostics:true});c(`syntax ${f}`,(out.diagnostics||[]).filter(d=>d.category===ts.DiagnosticCategory.Error).length===0)}
if(fail.length){console.error(`CP11 acceptance: FAIL (${fail.length})`);process.exit(1)} console.log('CP11 persistence/backtest UI acceptance: PASS');
